scripts/generate_embeddings.py

Generate docs_url metadata element for every node of content as embeddings are generated.
Matching OSL PR: https://github.com/openshift/lightspeed-service/pull/658
Jira: https://issues.redhat.com/browse/OLS-338

OLS-338: Add docs_url metadata element while creating embedding index

---

scripts/get_ocp_plaintext_docs.sh

In the scripts/get_ocp_plaintext_docs.sh script, delete the local copy of the docs so that the pages deleted in the upstream end up deleted in the local copy.

Delete the local copy of the OCP docs before update

---

scripts/query_rag.py

Added a script for querying the RAG database: scripts/query_rag.py. Usage example:
```
$ python scripts/query_rag.py -p ~/lightspeed-config/vector_db/ocp_product_docs/4.15 -x ocp-product-docs-4_15
-m ~/lightspeed-config/embeddings_model -q "what is kubernetes?" -k 5
LLM is explicitly disabled. Using MockLLM.
NodeWithScore(node=TextNode(id_='36d30b35-1440-4372-b2b8-1cbff69a70fd', embedding=None, metadata={'docs_url':
'https://docs.openshift.com/container-platform/4.15/architecture/architecture.html', 'title': '"Red Hat OpenShift Container 
Platform" architecture'}, excluded_embed_metadata_keys=['file_name', 'file_type', 'file_size', 'creation_date', 
'last_modified_date', 'last_accessed_date'], excluded_llm_metadata_keys=['file_name', 'file_type', 'file_size', 'creation_date', …
```

Added a script for querying the RAG database

---

scripts/generate_embeddings.py
scripts/query_rag.py

- Added a timeout to the docs URL liveness check
- Added detection of bad nodes: base64 chunks.
These are marked with `bad_node = 1` metadata label and are listed in the metadata.json file
- Added support for node lookup by node id

OLS-517: Handle encoded/image data in index

---

scripts/generate_embeddings.py

Raise exception instead of sys.exit when there are docs with invalid/unreachable url

OLS-623: raise exception for invalid url

---

scripts/asciidoctor-text/attributes.yaml
scripts/asciidoctor-text/convert-it-all.py
scripts/asciidoctor-text/text-converter.rb
scripts/generate_embeddings.py

Improvements to OCP docs plain text generation:
- Brought attributes from openshift-docs/blob/enterprise-4.15/_attributes/common-attributes.adoc
- Removed surrounding double quotes from attribute values in the generated plaintext
- Added handling of (R) (registered trademark) sign
- "bad nodes" are now "nodes without whitespace" during embeddings generation

Improvements to OCP docs plain text generation:

---

.tekton/lightspeed-rag-content-pull-request.yaml
.tekton/lightspeed-rag-content-push.yaml

Fix for 
```
[User error] Validation failed for pipelinerun lightspeed-rag-content-on-pull-request-x2sqp with error
invalid input params for task deprecated-image-check: missing values for these params which have no
default values: [IMAGE_URL IMAGE_DIGEST]
```
according to https://github.com/konflux-ci/build-definitions/blob/main/task/deprecated-image-check/0.4/MIGRATION.md

Konflux: migration from 0.3 to 0.4

---

.tekton/lightspeed-rag-content-pull-request.yaml

In Konflux, increase timeout on the build-container task and the overall pipeline timeout.

In Konflux, increase timeout on the build-container task and the overall pipeline timeout

---

.tekton/lightspeed-rag-content-pull-request.yaml
scripts/generate_embeddings.py

Reduce chunk size. [OLS-558](https://issues.redhat.com//browse/OLS-558)
Below changes were added, but commented out (not removing, eventually we may end up doing this)
- Split document as per header & section. [OLS-601](https://issues.redhat.com//browse/OLS-601)
- Ability to exclude metadata during embedding. [OLS-609](https://issues.redhat.com//browse/OLS-609)
Konflux pipeline takes really long time now with these changes, as we are processing large number of smaller chunks for 2 different OCP doc version.. We will have to figure out how we can reduce the pipeline execution time. Meanwhile timeout duration is increased significantly in order to keep reduced chunk size changes, which is important (Other 2 changes are not that important, so commented out)

OLS-558: modify rag chunking

---

.tekton/lightspeed-rag-content-pull-request.yaml
.tekton/lightspeed-rag-content-push.yaml

Removed sbom-json-check tasks from Konflux pipelines, sbom-json-check is getting deprecated.

Removed sbom-json-check tasks from Konflux pipelines

---

.tekton/lightspeed-rag-content-pull-request.yaml
.tekton/lightspeed-rag-content-push.yaml

Update the Konflux pipelines to remove enterprise contract warnings
JIRA: https://issues.redhat.com/browse/OLS-1151

OLS-1151: Update the Konflux pipelines to remove enterprise contract warnings

---

.tekton/lightspeed-rag-content-pull-request.yaml
.tekton/lightspeed-rag-content-push.yaml

This must be a merge gone wrong at some point in the past. The renovate bot silently failed to parse .tekton/lightspeed-rag-content-pu*.yaml and stopped updating the Konflux task references.

OLS-1255: Fix rag-content Tekton descriptors to make the renovate bot happy

---

.tekton/lightspeed-rag-content-pull-request.yaml
.tekton/lightspeed-rag-content-push.yaml

Add project and org to the Konflux Snyk task so Snyk scan results are sent to snyk.io.

OLS-1271: Add project and org to the Konflux Snyk task

---

Containerfile

Use `cp` instead of `ln -s` -> for hermetic from cachi2
Use `curl` instead of `wget` -> for non-hermetic

fix: modify how safetensor file is fetched

---

.tekton/lightspeed-rag-content-pull-request.yaml
.tekton/lightspeed-rag-content-push.yaml

Pick up buildah-remote task definition that reenables GPU support: https://github.com/konflux-ci/build-definitions/pull/1951

Pick up buildah-remote task definition that reenables GPU support

---

.syft.yaml

Excluded plaintext docs dirs from Syft scanning for requirements.txt
JIRA: https://issues.redhat.com/browse/KFLUXSPRT-2242

KFLUXSPRT-2242: Excluded plaintext docs dirs from Syft scanning for requirements.txt

---

.tekton/own-app-lightspeed-rag-content-pull-request.yaml
.tekton/own-app-lightspeed-rag-content-push.yaml

Disable image index build to work around buildah x-platform issue https://github.com/containers/buildah/issues/6091.

Disable image index build to work around buildah x-platform issue

---

Containerfile

Here we add a symlink to the latest version of OCP docs' RAG index
On the service side, it will look for the `default` directory if a RAG path does not exist.

OLS-1340: add default symlink to the latest version of OCP docs

---

ubi.repo

The RPM repo names must be on the https://github.com/release-engineering/rhtap-ec-policy/blob/main/data/known_rpm_repositories.yml list to avoid EC exceptions for RPMs installed from them.

Correct RPM repo names to avoid EC exceptions for RPMs

---

byok/README.md

Added a mention in the BYOK tool README that the Markdown files must have .md extensions.

Added a mention in the BYOK tool README that the Markdown files must have .md extensions.

---

scripts/html_chunking/html-stripper.py

on 23 HTML index files
w/o the fix:
stripping: ~30 sec
total_chunks: 11512
w/ fix:
stripping: ~20 sec
total_chunks: 8636
reduce in chunk reduces the final embedding
from
``` html
<h2>
Chapter 1. Overview
<rh-tooltip>
<rh-button>
<rh-icon>
</rh-icon>
</rh-button>
<div>
Copy link
Link copied to clipboard!
<rh-icon>
</rh-icon>
</div>
</rh-tooltip>
</h2>
```
to
```
<h2>
Chapter 1. Overview
</h2>
```

remove tooltip after each section title which stripping html

---

byok/Containerfile.tool

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini

chore(KONFLUX-6210): fix and set name and cpe label for lightspeed-rag-tool
