openshift/lightspeed-rag-content

- .tekton/lightspeed-rag-content-pull-request.yaml
- .tekton/lightspeed-rag-content-push.yaml
Enable building of the source image in Konflux
> Konflux: build source image

- scripts/generate_embeddings.py
A follow-up to https://github.com/openshift/lightspeed-rag-content/pull/9
The generate_embeddings.py script now keeps processing if unreachable docs URLs are found, but marks them with UNREACHABLE in the log and exits with an error and exit code 1.
```
file_path: /workdir/ocp-product-docs-plaintext/4.15/applications/working_with_helm_charts/odc-working-with-helm-releases.txt, title: Working with Helm releases, docs_url: https://docs.openshift.com/container-platform/4.15/applications/working_with_helm_charts/odc-working-with-helm-releases.html, UNREACHABLE
file_path: /workdir/ocp-product-docs-plaintext/4.15/applications/working_with_helm_charts/understanding-helm.txt, title: Understanding Helm, docs_url: https://docs.openshift.com/container-platform/4.15/applications/working_with_helm_chart …
```
> OLS-459: mark all unreachable URLs in the output and fail if any are found

- scripts/distance.py
Utility script to calculate distance between two sentences.
Extracted from https://github.com/openshift/lightspeed-service/blob/main/tests/scripts/validate_response.py
> Utility script to calculate distance between two sentences.

- scripts/generate_embeddings.py
Changing from L2 to IP faiss index to have score 0-1 range.
> OLS-493: Use faiss FlatIP index

- pdm.lock
- pyproject.toml
Updated Python dependencies
JIRA: https://issues.redhat.com/browse/OLS-649
> OLS-649: Update dependencies across all repos

- .tekton/lightspeed-rag-content-push.yaml
Sync timeouts in the pull and push Konflux pipelines
> Sync timeouts in the pull and push Konflux pipelines

- pdm.lock
- pyproject.toml
[OLS-649](https://issues.redhat.com//browse/OLS-649): Update dependencies across all repos - 2024/06/28
> OLS-649: Update dependencies across all repos - 2024/06/28

- scripts/download_embeddings_model.py
- scripts/generate_embeddings.py
> OLS-823: Sanitize local directory

- pdm.lock
- pyproject.toml
Bump-up llama-index and faiss-cpu dependencies
> Bump-up llama-index and faiss-cpu dependencies

- .tekton/lightspeed-rag-content-pull-request.yaml
- .tekton/lightspeed-rag-content-push.yaml
Use Konflux task images from quay.io/konflux-ci/tekton-catalog
> Use Konflux task images from quay.io/konflux-ci/tekton-catalog

- Containerfile
Added image labels to satisfy EC
> Added image labels to satisfy EC

- .tekton/lightspeed-rag-content-pull-request.yaml
- .tekton/lightspeed-rag-content-push.yaml
Migrating to resolve ecosystem-cert-preflight-checks in konflux EC
> migrate task-buildah to version  0.2

- .tekton/lightspeed-rag-content-pull-request.yaml
- .tekton/lightspeed-rag-content-push.yaml
Added a build-manifest task as the build-container runs as a multi-platform build.
> Added a build-manifest task

- Containerfile
This resolves the preflight checkes issues:
```json
{
"passed": [
{
"name": "HasUniqueTag",
"elapsed_time": 0,
"description": "Checking if container has a tag other than 'latest', so that the image can be uniquely identified."
},
{
"name": "LayerCountAcceptable",
"elapsed_time": 0,
"description": "Checking if container has less than 40 layers.  Too many layers within the container images can degrade container performance."
},
{
"name": "HasRequiredLabel",
"elapsed_time": 0,
"description": "Checking if the required labels (name, vendor, version, release, summary, description) are present in the container metadata."
}
],
"failed": [
{
"name": "HasLicense",
"elapsed_time": 0,
"description": "Checking if terms and conditions applicable to the software including open source licensing …
```
> konflux: fix enterprise contract issues

- .tekton/lightspeed-rag-content-pull-request.yaml
- .tekton/lightspeed-rag-content-push.yaml
- Makefile
- pdm.lock
pdm lock --refresh missed the last time pyproject.toml was updated
> pdm lock --refresh missed the last time

- pdm.lock
- pyproject.toml
Dependencies update.
`dev`
black==24.4.2 -> black==24.10.0
mypy==1.10.0 -> mypy==1.12.0
ruff==0.4.6 -> ruff==0.6.9
types-requests==2.31.0 -> types-requests==2.32.0.20240622
`prod`
llama_index==0.10.55 -> llama-index==0.10.62
[OLS-1142](https://issues.redhat.com//browse/OLS-1142)
> Bump up dependencies

- .tekton/buildah-remote.yaml
- .tekton/lightspeed-rag-content-push.yaml
Switch the on-push pipeline to GPU
> Switch the on-push pipeline to GPU

- .tekton/lightspeed-rag-content-pull-request.yaml
- .tekton/lightspeed-rag-content-push.yaml
Use a local override for the GPU-aware buildah-remote task
> Use a local override for the GPU-aware buildah-remote task

- .tekton/buildah-remote.yaml
Update the buildah-remote task from the Konflux upstream
> Update the buildah-remote task from the Konflux upstream

- Containerfile
> OLS-1523: Update to CUDA 12.8.1

- .tekton/own-app-lightspeed-rag-content-pull-request.yaml
- .tekton/own-app-lightspeed-rag-content-push.yaml
Sync Konflux descriptor details from old to new
> Sync Konflux descriptor details from old to new

- .tekton/own-app-lightspeed-rag-content-pull-request.yaml
- .tekton/own-app-lightspeed-rag-content-push.yaml
Add retries of 5 to all the tasks downstream of build-container
> Add retries of 5 to all the tasks downstream of build-container

- .tekton/integration-tests/lightspeed-rag-content-image-verification.yaml
Fix the integration test after the move to own app in [OLS-1304](https://issues.redhat.com//browse/OLS-1304)
JIRA: https://issues.redhat.com/browse/OLS-1304
> OLS-1304: Fix the integration test after the move to own app

- byok/Containerfile.output
- byok/Containerfile.output.builder
- byok/Containerfile.tool
- byok/README.md
- byok/generate_embeddings_tool.py
[OLS-1416](https://issues.redhat.com//browse/OLS-1416): BYOK: RAG database generation tool
> OLS-1416: BYOK: RAG database generation tool

- .tekton/own-app-lightspeed-rag-content-pull-request.yaml
- .tekton/own-app-lightspeed-rag-content-push.yaml
chore(deps): update konflux references 2025/04/19
JIRA: https://issues.redhat.com/browse/OLS-1683
> chore(deps): update konflux references 2025/04/19

- byok/Containerfile.output
- byok/Containerfile.tool
- byok/README.md
Added build arguments BYOK_TOOL_IMAGE and UBI_BASE_IMAGE for BYOK tool and UBI base image tags, respectively.
Added a LOG_LEVEL environment variable for buildah log level.
JIRA: https://issues.redhat.com/browse/OLS-1659
> OLS-1659: BYOK tool: added build args BYOK_TOOL_IMAGE and UBI_BASE_IMAGE, LOG_LEVEL env var

- .tekton/own-app-lightspeed-rag-content-pull-request.yaml
- .tekton/own-app-lightspeed-rag-content-push.yaml
chore(deps): update konflux references 2025/04/26
> chore(deps): update konflux references 2025/04/26

- scripts/html_chunking/html-stripper.py
@syedriko Could you PTAL? Thank you.
> OLS-1499 Add script for removing ballast content from OpenShift documentation

- pdm.lock.cpu
- pdm.lock.gpu
- pyproject.toml
- scripts/asciidoctor-text/convert-it-all.py
- scripts/generate_packages_to_prefetch.py
- scripts/portal-fetcher/openshift-docs-downloader.py
- scripts/verify_rag_image_test.py
@syedriko Could you PTAL? Thank you.
> OLS-1651 Add script for fetching OpenShift documentation in the HTML format

- .tekton/lightspeed-rag-tool-pull-request.yaml
- .tekton/lightspeed-rag-tool-push.yaml
- .tekton/own-app-lightspeed-rag-content-pull-request.yaml
- .tekton/own-app-lightspeed-rag-content-push.yaml
Update all Konflux task references except for prefetch
JIRA: OLS-1717, [KFLUXSPRT-2905](https://issues.redhat.com//browse/KFLUXSPRT-2905)
> Update Konflux task references except for prefetch

- .tekton/lightspeed-rag-tool-pull-request.yaml
- .tekton/lightspeed-rag-tool-push.yaml
- Makefile
- byok/Containerfile.output
- byok/Containerfile.tool
- rpms.in.yaml
- rpms.lock.yaml
- ubi.repo
[OLS-1676](https://issues.redhat.com//browse/OLS-1676): Create RAG BYOK tool image through Konflux
JIRA: https://issues.redhat.com/browse/OLS-1676
> OLS-1676: Create RAG BYOK tool image through Konflux

- .tekton/lightspeed-rag-tool-push.yaml
Fix the on push  tekton file - currently the on-push job is not running in konflux.
> update on-push tekton file

- scripts/html_chunking/chunker.py
- scripts/html_chunking/html-stripper.py
- scripts/html_chunking/test_chunker.py
- scripts/html_embeddings/chunk_html.py
(This is a fix and improvement for https://github.com/openshift/lightspeed-rag-content/pull/439/)
@tisnik Could you PTAL?
> LCORE-307 Fix `title` bug; simplify & update test; add `section_title` metadata

- renovate.json
Added renovate.json file to increase the number of concurrent PRs from MintMaker
JIRA: https://issues.redhat.com/browse/KFLUXSPRT-4218
> Added renovate.json file to increase the number of concurrent PRs from MintMaker
